(function(){
  if(window.__ARIA_BRAIN_V1)return;window.__ARIA_BRAIN_V1=true;
  const cfg=window.ARIA_CLOUD||{};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  let history=[];

  function getDB(){try{return typeof db!=='undefined'?db:null}catch{return null}}
  function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
  function findToken(obj,depth=0){if(!obj||depth>6)return'';if(typeof obj==='object'){if(typeof obj.access_token==='string'&&obj.access_token.trim())return obj.access_token.trim();for(const k of Object.keys(obj)){const v=findToken(obj[k],depth+1);if(v)return v}}return''}
  function getToken(){try{const preferred=`sb-${new URL(cfg.supabaseUrl).hostname.split('.')[0]}-auth-token`;const keys=[preferred,...Object.keys(localStorage).filter(k=>k.startsWith('sb-')&&k.includes('auth-token'))];for(const k of [...new Set(keys)]){const raw=localStorage.getItem(k);if(!raw)continue;try{const t=findToken(JSON.parse(raw));if(t)return t}catch(_){}}}catch(_){}throw new Error('برای هوش مصنوعی باید وارد حساب ARIA باشی.');}
  function snapshot(){const D=getDB()||{};const tasks=(D.tasks||[]).map(t=>({id:t.id,title:t.title,project:t.project,area:t.area,description:t.description,date:t.date,time:t.time,priority:t.priority,status:t.status,repeat:t.repeat,subtasks:t.subtasks||[]}));const projects=(D.projects||[]).map(p=>({id:p.id,name:p.name,area:p.area,desc:p.desc}));const music=(D.music||[]).map(m=>({id:m.id,type:m.type,title:m.title,date:m.date,duration:m.duration,note:m.note}));return{today:today(),currentView:typeof view!=='undefined'?view:null,currentProject:typeof currentProject!=='undefined'?currentProject:null,searchText:typeof searchText!=='undefined'?searchText:null,tasks,projects,music};}
  async function askAI(query){const token=getToken();const r=await fetch(`/api/aria-ai?mode=assistant&t=${encodeURIComponent(token)}&v=1`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,context:snapshot(),history})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out?.detail||out?.error||`خطای سرور ${r.status}`);const text=String(out.text||'').trim();history.push({role:'user',text:query},{role:'assistant',text});history=history.slice(-12);return text}
  function localFallback(q){const D=getDB()||{},tasks=(D.tasks||[]).filter(t=>t.status!=='done'),td=today();const overdue=tasks.filter(t=>t.date&&t.date<td),todayTasks=tasks.filter(t=>t.date===td);if(/عقب|دیر/.test(q))return overdue.length?`کارهای عقب‌افتاده:\n${overdue.map((t,i)=>`${i+1}) ${t.title}`).join('\n')}`:'کار عقب‌افتاده نداری.';if(/امروز|اولویت|چی کار/.test(q)){const score=t=>(t.priority==='urgent'?30:t.priority==='important'?15:0)+(t.date&&t.date<td?40:0)+(t.date===td?20:0);return tasks.sort((a,b)=>score(b)-score(a)).slice(0,5).map((t,i)=>`${i+1}) ${t.title}`).join('\n')||'کار بازی نداری.'}return `ARIA الان به کل داده‌های برنامه وصل است: ${tasks.length} کار باز، ${overdue.length} عقب‌افتاده، ${(D.projects||[]).length} پروژه و ${(D.music||[]).length} ثبت موسیقی. برای تحلیل واقعی آنلاین، کلید OpenAI سرور باید معتبر باشد.`}

  function ensureUI(){if($('ariaBrainDialog'))return;const css=document.createElement('style');css.textContent=`#ariaBrainFab{position:fixed;left:16px;bottom:calc(86px + env(safe-area-inset-bottom));z-index:70;width:54px;height:54px;border-radius:18px;background:linear-gradient(135deg,#4f7cff,#2dd4bf);font-size:24px;box-shadow:0 12px 32px #0007}.ariaBrainAns{white-space:pre-wrap;line-height:1.9;background:#0d151c;border:1px solid var(--line);border-radius:13px;padding:11px;min-height:90px;margin-top:10px}.ariaBrainQuick{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.ariaBrainQuick button{font-size:11px}`;document.head.appendChild(css);
    const fab=document.createElement('button');fab.id='ariaBrainFab';fab.type='button';fab.title='مغز هوشمند ARIA';fab.textContent='✦';document.body.appendChild(fab);
    const d=document.createElement('dialog');d.id='ariaBrainDialog';d.innerHTML=`<div><div class="sectionHead"><b>✦ مغز هوشمند ARIA</b><button class="ghost" id="ariaBrainClose" type="button">بستن</button></div><div class="sub" style="margin:8px 0">ARIA کل کارها، پروژه‌ها، موسیقی و وضعیت جاری برنامه را در تحلیل می‌بیند.</div><textarea id="ariaBrainText" dir="rtl" placeholder="مثلاً: امروز از کجا شروع کنم؟ / کارهای عقب‌افتاده‌ام را جمع‌بندی کن / برای این هفته برنامه بچین"></textarea><div class="ariaBrainQuick"><button data-q="امروز از کجا شروع کنم؟">برنامه امروز</button><button data-q="کارهای عقب‌افتاده‌ام را بگو">عقب‌افتاده‌ها</button><button data-q="سه اولویت اصلی من چیست؟">۳ اولویت</button><button data-q="وضعیت همه پروژه‌ها را تحلیل کن">پروژه‌ها</button></div><button id="ariaBrainSend" class="primary" type="button" style="margin-top:9px">تحلیل هوشمند</button><div id="ariaBrainAnswer" class="ariaBrainAns">آماده‌ام.</div></div>`;document.body.appendChild(d);
    fab.onclick=()=>d.showModal();$('ariaBrainClose').onclick=()=>d.close();d.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('ariaBrainText').value=b.dataset.q;run()});$('ariaBrainSend').onclick=run;
  }
  async function run(){const q=$('ariaBrainText')?.value.trim();if(!q)return;const a=$('ariaBrainAnswer'),b=$('ariaBrainSend');b.disabled=true;a.textContent='در حال تحلیل کل ARIA…';try{a.textContent=await askAI(q)}catch(e){a.textContent=localFallback(q)+'\n\nوضعیت AI آنلاین: '+(e?.message||String(e))}finally{b.disabled=false}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(ensureUI,500));else setTimeout(ensureUI,500);
})();