(function(){
 if(window.__ARIA_MUSIC_SUITE_V1)return; window.__ARIA_MUSIC_SUITE_V1=true;
 const K={sessions:'ARIA_MUSIC_SESSIONS_V1',bpm:'ARIA_MUSIC_BPM_V1',songs:'ARIA_MUSIC_SONGS_V1',setlists:'ARIA_MUSIC_SETLISTS_V1',goals:'ARIA_MUSIC_GOALS_V1',plan:'ARIA_MUSIC_PLAN_V1'};
 const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const day=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
 const instruments=['کونگا','جمبه','درام','داربوکا','بانگو','بندیر','سایر'];
 let tick=null,startTs=0,elapsed=0,currentInstrument='کونگا';
 const css=document.createElement('style');css.textContent=`#ariaMusicPro{width:min(900px,96vw);max-height:92vh}.amTabs{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.amTabs button.active{outline:2px solid var(--accent)}.amGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.amCard{padding:13px;border:1px solid var(--line);border-radius:16px;background:var(--panel2)}.amList{display:grid;gap:8px}.amRow{padding:10px;border:1px solid var(--line);border-radius:13px;background:var(--panel)}.amBig{font-size:34px;font-weight:900;text-align:center}.amStats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.amStats>div{padding:9px;text-align:center;background:var(--panel);border-radius:12px}.amStats b{display:block;font-size:18px}.amForm{display:grid;gap:8px}.amInline{display:flex;gap:7px;flex-wrap:wrap}.amAI{padding:12px;border:1px solid var(--line);border-radius:14px;line-height:1.8;background:linear-gradient(135deg,color-mix(in srgb,var(--accent) 10%,var(--panel2)),var(--panel))}@media(max-width:700px){.amGrid{grid-template-columns:1fr}.amStats{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(css);
 function build(){if($('ariaMusicPro'))return;const d=document.createElement('dialog');d.id='ariaMusicPro';d.innerHTML=`<div class="sectionHead"><b>🎵 Music Pro</b><button id="amClose" class="ghost">بستن</button></div><div class="amTabs" id="amTabs"><button data-tab="practice" class="active">تمرین امروز</button><button data-tab="songs">بانک آهنگ</button><button data-tab="setlist">Setlist</button><button data-tab="goals">هدف‌ها</button><button data-tab="stats">آمار و AI</button></div><div id="amBody"></div>`;document.body.appendChild(d);$('amClose').onclick=()=>closeDialog(d);d.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{d.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.tab)});}
 function showDialog(d){try{if(d.showModal)d.showModal();else d.setAttribute('open','')}catch{d.setAttribute('open','')}} function closeDialog(d){try{d.close()}catch{d.removeAttribute('open')}}
 function render(tab){if(tab==='practice')renderPractice();if(tab==='songs')renderSongs();if(tab==='setlist')renderSetlist();if(tab==='goals')renderGoals();if(tab==='stats')renderStats();}
 function renderPractice(){const plan=read(K.plan);const todayPlan=plan.filter(x=>x.date===day());$('amBody').innerHTML=`<div class="amGrid"><div class="amCard"><b>برنامه تمرین امروز</b><div class="amForm" style="margin-top:9px"><select id="amPlanInst">${instruments.map(x=>`<option>${x}</option>`).join('')}</select><input id="amPlanTopic" placeholder="موضوع تمرین؛ مثلاً رول یا قطعه استاد"><input id="amPlanMin" type="number" min="1" value="20" placeholder="دقیقه"><button class="primary" id="amAddPlan">افزودن به امروز</button></div><div id="amPlanList" class="amList" style="margin-top:10px"></div></div><div class="amCard"><b>تایمر تمرین</b><select id="amTimerInst" style="margin-top:9px">${instruments.map(x=>`<option>${x}</option>`).join('')}</select><div id="amTimer" class="amBig">00:00</div><div class="amInline"><button class="primary" id="amStart">شروع</button><button id="amStop">پایان و ثبت</button></div><div style="margin-top:12px"><b>ثبت BPM</b><div class="amInline" style="margin-top:7px"><select id="amBpmInst">${instruments.map(x=>`<option>${x}</option>`).join('')}</select><input id="amBpmTopic" placeholder="تکنیک/قطعه"><input id="amBpm" type="number" min="20" max="300" placeholder="BPM"><button id="amSaveBpm">ثبت</button></div></div></div></div>`;
 $('amAddPlan').onclick=()=>{const a=read(K.plan);a.push({id:Date.now(),date:day(),instrument:$('amPlanInst').value,topic:$('amPlanTopic').value.trim(),minutes:+$('amPlanMin').value||20,done:false});write(K.plan,a);renderPractice()};
 $('amStart').onclick=()=>{if(tick)return;currentInstrument=$('amTimerInst').value;startTs=Date.now();tick=setInterval(()=>{const s=Math.floor((elapsed+Date.now()-startTs)/1000);$('amTimer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},500)};
 $('amStop').onclick=()=>{if(!tick&&elapsed===0)return;const totalMs=elapsed+(tick?Date.now()-startTs:0);clearInterval(tick);tick=null;elapsed=0;const a=read(K.sessions);a.push({id:Date.now(),date:day(),ts:Date.now(),instrument:currentInstrument,minutes:Math.max(1,Math.round(totalMs/60000))});write(K.sessions,a);$('amTimer').textContent='00:00';renderPractice()};
 $('amSaveBpm').onclick=()=>{const a=read(K.bpm);a.push({id:Date.now(),date:day(),ts:Date.now(),instrument:$('amBpmInst').value,topic:$('amBpmTopic').value.trim(),bpm:+$('amBpm').value||0});write(K.bpm,a);$('amBpm').value='';$('amBpmTopic').value=''};
 const list=$('amPlanList');list.innerHTML=todayPlan.length?todayPlan.map(x=>`<div class="amRow"><b>${esc(x.instrument)} · ${esc(x.topic||'تمرین')}</b><div class="sub">${x.minutes} دقیقه</div><button data-done="${x.id}" style="margin-top:6px">${x.done?'✓ انجام شد':'علامت انجام'}</button></div>`).join(''):'برای امروز برنامه‌ای ثبت نشده.';list.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const a=read(K.plan),i=a.findIndex(x=>String(x.id)===b.dataset.done);if(i>=0)a[i].done=!a[i].done;write(K.plan,a);renderPractice()});}
 function renderSongs(){const songs=read(K.songs);$('amBody').innerHTML=`<div class="amGrid"><div class="amCard"><b>افزودن آهنگ</b><div class="amForm" style="margin-top:9px"><input id="amSongName" placeholder="نام آهنگ"><input id="amSinger" placeholder="خواننده"><input id="amSongBpm" type="number" placeholder="BPM"><input id="amRhythm" placeholder="ریتم / سبک"><textarea id="amSongNotes" placeholder="نکات اجرا، ورودها، رول، Break و ..."></textarea><button class="primary" id="amAddSong">ذخیره آهنگ</button></div></div><div class="amCard"><b>بانک آهنگ‌ها</b><input id="amSongSearch" placeholder="جستجو" style="margin-top:8px"><div id="amSongList" class="amList" style="margin-top:8px"></div></div></div>`;$('amAddSong').onclick=()=>{const a=read(K.songs);a.push({id:Date.now(),name:$('amSongName').value.trim(),singer:$('amSinger').value.trim(),bpm:+$('amSongBpm').value||0,rhythm:$('amRhythm').value.trim(),notes:$('amSongNotes').value.trim()});write(K.songs,a);renderSongs()};function draw(q=''){const f=songs.filter(x=>(x.name+' '+x.singer+' '+x.rhythm).includes(q));$('amSongList').innerHTML=f.length?f.map(x=>`<div class="amRow"><b>${esc(x.name)}</b><div class="sub">${esc(x.singer)}${x.bpm?' · '+x.bpm+' BPM':''}${x.rhythm?' · '+esc(x.rhythm):''}</div>${x.notes?`<div style="margin-top:5px">${esc(x.notes)}</div>`:''}<button data-del-song="${x.id}" class="danger" style="margin-top:6px">حذف</button></div>`).join(''):'آهنگی ثبت نشده.';$('amSongList').querySelectorAll('[data-del-song]').forEach(b=>b.onclick=()=>{write(K.songs,read(K.songs).filter(x=>String(x.id)!==b.dataset.delSong));renderSongs()})}draw();$('amSongSearch').oninput=e=>draw(e.target.value.trim());}
 function renderSetlist(){const songs=read(K.songs),sets=read(K.setlists);$('amBody').innerHTML=`<div class="amGrid"><div class="amCard"><b>ساخت Setlist</b><div class="amForm" style="margin-top:9px"><input id="amSetName" placeholder="نام اجرا / تاریخ / محل"><textarea id="amSetSongs" placeholder="ترتیب آهنگ‌ها را هر خط یک آهنگ بنویس"></textarea><button id="amFillSongs">قرار دادن نام آهنگ‌های بانک</button><button class="primary" id="amSaveSet">ذخیره Setlist</button></div></div><div class="amCard"><b>Setlistها</b><div id="amSetList" class="amList" style="margin-top:8px"></div></div></div>`;$('amFillSongs').onclick=()=>{$('amSetSongs').value=songs.map(x=>x.name).join('\n')};$('amSaveSet').onclick=()=>{const a=read(K.setlists);a.push({id:Date.now(),name:$('amSetName').value.trim()||'اجرای جدید',songs:$('amSetSongs').value.split('\n').map(x=>x.trim()).filter(Boolean)});write(K.setlists,a);renderSetlist()};$('amSetList').innerHTML=sets.length?sets.map(x=>`<div class="amRow"><b>${esc(x.name)}</b><ol>${(x.songs||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><button data-del-set="${x.id}" class="danger">حذف</button></div>`).join(''):'Setlist ثبت نشده.';$('amSetList').querySelectorAll('[data-del-set]').forEach(b=>b.onclick=()=>{write(K.setlists,read(K.setlists).filter(x=>String(x.id)!==b.dataset.delSet));renderSetlist()});}
 function renderGoals(){const g=read(K.goals);$('amBody').innerHTML=`<div class="amGrid"><div class="amCard"><b>هدف موسیقی</b><div class="amForm" style="margin-top:9px"><input id="amGoal" placeholder="مثلاً رول تمیز روی 120 BPM"><input id="amGoalDate" type="date"><button class="primary" id="amAddGoal">ثبت هدف</button></div></div><div class="amCard"><b>هدف‌ها</b><div id="amGoalList" class="amList" style="margin-top:8px"></div></div></div>`;$('amAddGoal').onclick=()=>{const a=read(K.goals);a.push({id:Date.now(),title:$('amGoal').value.trim(),date:$('amGoalDate').value,done:false});write(K.goals,a);renderGoals()};$('amGoalList').innerHTML=g.length?g.map(x=>`<div class="amRow"><b>${x.done?'✓ ':''}${esc(x.title)}</b><div class="sub">${esc(x.date||'بدون تاریخ')}</div><button data-goal="${x.id}">${x.done?'باز کردن':'انجام شد'}</button></div>`).join(''):'هدفی ثبت نشده.';$('amGoalList').querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{const a=read(K.goals),i=a.findIndex(x=>String(x.id)===b.dataset.goal);if(i>=0)a[i].done=!a[i].done;write(K.goals,a);renderGoals()});}
 function weekData(){const from=Date.now()-6*86400000;const s=read(K.sessions).filter(x=>(x.ts||0)>=from),b=read(K.bpm).filter(x=>(x.ts||0)>=from);return{s,b,total:s.reduce((n,x)=>n+(x.minutes||0),0)}}
 async function renderStats(){const w=weekData(),by={};w.s.forEach(x=>by[x.instrument]=(by[x.instrument]||0)+(x.minutes||0));const top=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];const bpms=w.b.filter(x=>x.bpm).sort((a,b)=>b.bpm-a.bpm);$('amBody').innerHTML=`<div class="amCard"><div class="amStats"><div><b>${w.total}</b><span>دقیقه این هفته</span></div><div><b>${w.s.length}</b><span>جلسه تمرین</span></div><div><b>${top?esc(top[0]):'-'}</b><span>بیشترین ساز</span></div><div><b>${bpms[0]?.bpm||'-'}</b><span>بالاترین BPM</span></div></div></div><div class="amGrid" style="margin-top:12px"><div class="amCard"><b>پیشنهاد تمرین هوشمند</b><div id="amSuggest" class="amAI" style="margin-top:8px"></div></div><div class="amCard"><b>تحلیل AI تمرین</b><div id="amAnalysis" class="amAI" style="margin-top:8px">برای تحلیل، دکمه زیر را بزن.</div><button id="amAnalyze" class="primary" style="margin-top:8px">تحلیل این هفته</button></div></div>`;const least=instruments.map(i=>[i,by[i]||0]).sort((a,b)=>a[1]-b[1])[0];$('amSuggest').textContent=w.total===0?'هنوز تمرینی برای این هفته ثبت نشده.':`این هفته ${w.total} دقیقه تمرین داشتی. برای تعادل، جلسه بعدی را روی ${least[0]} بگذار.${bpms.length?' بالاترین BPM ثبت‌شده '+bpms[0].bpm+' بوده.':''}`;$('amAnalyze').onclick=async()=>{const box=$('amAnalysis');box.textContent='در حال تحلیل…';const payload={weeklyMinutes:w.total,sessions:w.s,bpm:w.b,goals:read(K.goals),plan:read(K.plan).filter(x=>x.date>=day())};try{if(window.ARIA_BRAIN?.ask){const r=await window.ARIA_BRAIN.ask('این داده‌های تمرین موسیقی من را تحلیل کن، کوتاه و کاربردی بگو پیشرفتم چطور بوده، ضعف اصلی چیست و فردا دقیقاً چه تمرینی انجام بدهم: '+JSON.stringify(payload));box.textContent=r?.text||String(r)}else{box.textContent=`این هفته ${w.total} دقیقه در ${w.s.length} جلسه تمرین ثبت شده. ${least[0]} کمتر از بقیه تمرین شده؛ فردا 20 دقیقه روی آن بگذار و 10 دقیقه هم روی تکنیکی که BPM آن پایین‌تر است کار کن.`}}catch{box.textContent='تحلیل AI فعلاً در دسترس نیست؛ آمار محلی همچنان ثبت می‌شود.'}};}
 function open(){build();render('practice');showDialog($('ariaMusicPro'))}
 function inject(){document.querySelectorAll('[data-view="music"]').forEach(b=>{if(b.dataset.amHook)return;b.dataset.amHook='1';b.addEventListener('click',()=>setTimeout(()=>{const main=$('main');if(main&&!$('amMusicProBtn')){const wrap=document.createElement('div');wrap.className='card section';wrap.id='amMusicProBtn';wrap.innerHTML='<div class="sectionHead"><b>🎵 مرکز حرفه‌ای موسیقی</b><button class="primary" id="amOpenMusicPro">باز کردن</button></div><div class="sub">تمرین، تایمر، BPM، آهنگ‌ها، Setlist، هدف‌ها و تحلیل هوشمند</div>';main.prepend(wrap);$('amOpenMusicPro').onclick=open}},120))})}
 build();inject();new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});window.ARIA_MUSIC_PRO_OPEN=open;
})();