(function(){
  if(window.__ARIA_NOTIFY_V6)return;window.__ARIA_NOTIFY_V6=true;
  const cfg=window.ARIA_CLOUD||{};
  const VAPID_PUBLIC='BBLpNEz_gYbTWB0GR3hVxTwsHNOOlplYH06E-KraiPJTO1Yz037extmkp7VENUkgD37UvDFPTIpYqidHpF6tNpw';
  const $=id=>document.getElementById(id);
  const endpoint=(path)=>`${String(cfg.supabaseUrl||'').replace(/\/$/,'')}${path}`;
  function findToken(obj,depth=0){if(!obj||depth>6)return'';if(typeof obj==='object'){if(typeof obj.access_token==='string'&&obj.access_token.trim())return obj.access_token.trim();for(const k of Object.keys(obj)){const v=findToken(obj[k],depth+1);if(v)return v}}return''}
  function getToken(){try{const ref=new URL(cfg.supabaseUrl).hostname.split('.')[0];for(const k of [`sb-${ref}-auth-token`,...Object.keys(localStorage).filter(k=>k.startsWith('sb-')&&k.includes('auth-token'))]){const raw=localStorage.getItem(k);if(!raw)continue;try{const t=findToken(JSON.parse(raw));if(t)return t}catch(_){}}}catch(_){}return''}
  function deviceName(){const ua=navigator.userAgent||'';if(/iPad/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1))return'ARIA iPad';if(/iPhone/.test(ua))return'ARIA iPhone';return'ARIA device'}
  function standalone(){return window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true}
  function b64ToUint8(s){const p='='.repeat((4-s.length%4)%4);const b=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...b].map(c=>c.charCodeAt(0)))}
  async function getPublicKey(){try{const r=await fetch('/api/aria-notify?public_key=1',{cache:'no-store'});const o=await r.json().catch(()=>({}));if(r.ok&&o.publicKey)return o.publicKey}catch(_){}return VAPID_PUBLIC}
  async function saveSubscription(sub){const token=getToken();if(!token)throw new Error('اول باید وارد حساب ARIA باشی.');const ref=new URL(cfg.supabaseUrl).hostname.split('.')[0];let owner='';try{const x=JSON.parse(localStorage.getItem(`sb-${ref}-auth-token`)||'{}');owner=x?.user?.id||x?.currentSession?.user?.id||x?.session?.user?.id||''}catch(_){}if(!owner){const p=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));owner=p.sub||''}const body={owner_id:owner,device_name:deviceName(),endpoint:sub.endpoint,subscription:sub.toJSON(),updated_at:new Date().toISOString()};const r=await fetch(endpoint('/rest/v1/aria_push_subscriptions?on_conflict=owner_id,endpoint'),{method:'POST',headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});if(!r.ok)throw new Error('ثبت این دستگاه انجام نشد.')}
  async function remoteTest(){const token=getToken();if(!token)throw new Error('توکن ورود پیدا نشد.');const r=await fetch('/api/aria-notify?mode=test',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}',cache:'no-store'});const o=await r.json().catch(()=>({}));if(!r.ok)throw new Error(o?.detail||o?.error||'تست پوش ارسال نشد');return o}
  async function freshSubscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Push واقعی روی این دستگاه پشتیبانی نمی‌شود.');const oldRegs=await navigator.serviceWorker.getRegistrations();for(const r of oldRegs){try{const s=await r.pushManager.getSubscription();if(s)await s.unsubscribe()}catch(_){}}const reg=await navigator.serviceWorker.register('./sw.js?v=26',{scope:'./'});await navigator.serviceWorker.ready;const key=b64ToUint8(await getPublicKey());const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});return sub}
  async function subscribe(){if(!('Notification'in window))throw new Error('این دستگاه اعلان پوش را پشتیبانی نمی‌کند.');if(/iPhone|iPad/.test(navigator.userAgent||'')&&!standalone())throw new Error('ARIA را از آیکن Home Screen باز کن.');let perm=Notification.permission;if(perm==='default')perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('اجازه اعلان خاموش است.');const sub=await freshSubscription();await saveSubscription(sub);localStorage.setItem('ARIA_PUSH_READY','1');localStorage.setItem('ARIA_PUSH_MODE','sw-v6');const result=await remoteTest();if(!result?.sent)throw new Error('Push آزمایشی ارسال نشد.');updateBell(true);return true}
  async function ensureGranted(){if(Notification?.permission!=='granted')return false;try{const reg=await navigator.serviceWorker.register('./sw.js?v=26',{scope:'./'});await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const key=b64ToUint8(await getPublicKey());sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key})}await saveSubscription(sub);localStorage.setItem('ARIA_PUSH_READY','1');localStorage.setItem('ARIA_PUSH_MODE','sw-v6');updateBell(true);return true}catch(e){localStorage.removeItem('ARIA_PUSH_READY');updateBell(false);return false}}
  function updateBell(ok){const b=$('ariaNotifyBell');if(!b)return;b.textContent=ok?'🔔':'🔕';b.style.borderColor=ok?'#2dd4bf':'#ffb84a'}
  function makeBell(){if($('ariaNotifyBell'))return;const b=document.createElement('button');b.id='ariaNotifyBell';b.type='button';b.textContent=localStorage.getItem('ARIA_PUSH_READY')==='1'?'🔔':'🔕';b.style.cssText='position:fixed;right:14px;bottom:calc(138px + env(safe-area-inset-bottom));z-index:2147482990;width:54px;height:54px;border-radius:18px;border:2px solid #2dd4bf;background:#101820;color:#fff;font-size:23px;box-shadow:0 10px 28px rgba(0,0,0,.42);display:block!important';b.onclick=()=>makePrompt(true);(document.body||document.documentElement).appendChild(b)}
  function removePrompt(){document.getElementById('ariaNotifyPrompt')?.remove()}
  function makePrompt(force=false,err=''){if($('ariaNotifyPrompt'))return;const box=document.createElement('div');box.id='ariaNotifyPrompt';box.style.cssText='position:fixed;left:12px;right:12px;top:calc(12px + env(safe-area-inset-top));z-index:2147483000;background:#111a22;border:1px solid #2dd4bf;border-radius:16px;padding:12px 13px;box-shadow:0 14px 40px #0009;color:#f3f7f9;direction:rtl';box.innerHTML=`<div style="font-weight:900;margin-bottom:5px">🔔 اعلان‌های ARIA</div><div style="font-size:12px;line-height:1.8;color:#c8d5db">این بار ثبت Push از صفر بازسازی می‌شود تا با برنامه بسته هم کار کند.</div><div style="display:flex;gap:8px;margin-top:9px"><button id="ariaNotifyEnable" class="primary" style="flex:1">بازسازی و تست Push</button><button id="ariaNotifyLater" class="ghost">بستن</button></div><div id="ariaNotifyMsg" style="font-size:11px;margin-top:7px;color:#ffbd4a">${err||''}</div>`;document.body.appendChild(box);$('ariaNotifyEnable').onclick=async()=>{const b=$('ariaNotifyEnable'),m=$('ariaNotifyMsg');b.disabled=true;m.textContent='در حال بازسازی ثبت Push…';try{await subscribe();m.style.color='#42d392';m.textContent='ثبت جدید انجام شد ✓ تست باید همین حالا بیاد.';setTimeout(removePrompt,2600)}catch(e){localStorage.removeItem('ARIA_PUSH_READY');updateBell(false);m.textContent=e?.message||'فعال‌سازی انجام نشد.'}finally{b.disabled=false}};$('ariaNotifyLater').onclick=removePrompt}
  function boot(){makeBell();if(!('Notification'in window))return;if(localStorage.getItem('ARIA_PUSH_MODE')!=='sw-v6'){localStorage.removeItem('ARIA_PUSH_READY');setTimeout(()=>makePrompt(true),500);return}if(Notification.permission==='granted')ensureGranted();else if(Notification.permission==='default')setTimeout(()=>makePrompt(true),700);else updateBell(false)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.addEventListener('pageshow',boot);window.ARIA_NOTIFICATIONS={subscribe,refresh:ensureGranted,test:remoteTest,open:()=>makePrompt(true)};
})();