(function(){
  if(window.__ARIA_PRODUCTIVITY_SUITE_V1)return;window.__ARIA_PRODUCTIVITY_SUITE_V1=true;
  const $=id=>document.getElementById(id), LS=localStorage;
  const K={blocks:'ARIA_TIME_BLOCKS_V1',inbox:'ARIA_SMART_INBOX_V1',timers:'ARIA_TASK_TIMELOG_V1',backs:'ARIA_AUTO_BACKUPS_V1',energy:'ARIA_ENERGY_V1'};
  const read=(k,d=[])=>{try{return JSON.parse(LS.getItem(k)||JSON.stringify(d))}catch{return d}},write=(k,v)=>LS.setItem(k,JSON.stringify(v));
  const getDB=()=>{try{return typeof db!=='undefined'?db:null}catch{return null}};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const nowDate=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
  const tomorrowDate=()=>{const d=new Date();d.setDate(d.getDate()+1);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
  const css=document.createElement('style');css.textContent=`
  #ariaProdBtn{width:42px;height:42px;padding:0!important;font-size:18px;display:grid;place-items:center}
  #ariaProdDialog{width:min(980px,96vw);max-height:92vh}.apTabs{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 14px}.apTabs button.active{outline:2px solid var(--accent)}.apGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.apCard{padding:14px;border:1px solid var(--line);border-radius:16px;background:color-mix(in srgb,var(--panel2) 78%,transparent)}.apCard h4{margin:0 0 10px}.apMetric{font-size:28px;font-weight:900}.apBars{display:grid;gap:8px}.apBar{height:10px;background:var(--panel);border-radius:99px;overflow:hidden}.apBar i{display:block;height:100%;background:linear-gradient(90deg,var(--accent2),var(--accent));border-radius:99px}.apRow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.apList{display:grid;gap:7px}.apItem{padding:9px 10px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.apFull{grid-column:1/-1}@media(max-width:760px){.apGrid{grid-template-columns:1fr}.apFull{grid-column:auto}}
  `;document.head.appendChild(css);

  function taskInfo(){const D=getDB()||{}, tasks=Array.isArray(D.tasks)?D.tasks:[];return {D,tasks,open:tasks.filter(t=>t.status!=='done'),done:tasks.filter(t=>t.status==='done')};}
  function focusHist(){return read('ARIA_FOCUS_HISTORY_V1',[])}
  function timeLogs(){return read(K.timers,[])}
  function minsToday(){const td=nowDate();return focusHist().filter(x=>x.date===td).reduce((s,x)=>s+(+x.minutes||0),0)}
  function completedToday(){const td=nowDate();return taskInfo().done.filter(t=>String(t.completedAt||t.doneAt||t.updatedAt||'').slice(0,10)===td)}
  function dueToday(t){return String(t.date||t.dueDate||t.due||'').slice(0,10)===nowDate()}
  function overdue(t){const d=String(t.date||t.dueDate||t.due||'').slice(0,10);return d&&d<nowDate()&&t.status!=='done'}
  function score(){const ti=taskInfo(), done=completedToday().length, focus=minsToday(), od=ti.open.filter(overdue).length;return Math.max(0,Math.min(100,Math.round(done*12+Math.min(45,focus/2)-od*6+25)))}
  function bestHour(){const logs=timeLogs().filter(x=>x.end&&x.start);const by={};logs.forEach(x=>{const h=new Date(x.start).getHours();by[h]=(by[h]||0)+(x.minutes||0)});const e=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];return e?`${e[0]} تا ${(+e[0]+1)%24}`:'هنوز داده کافی نیست'}
  function pickTask(energy='medium'){const {open}=taskInfo();if(!open.length)return null;const ranked=[...open].sort((a,b)=>{const p=x=>x.priority==='urgent'?4:x.priority==='high'?3:x.priority==='medium'?2:1;return p(b)-p(a)});if(energy==='low')return ranked.find(x=>(x.estimate||x.duration||30)<=30)||ranked[0];if(energy==='high')return ranked[0];return ranked.find(x=>!overdue(x))||ranked[0]}
  function smartClassify(text){const s=text.toLowerCase();if(/جلسه|meeting|قرار/.test(s))return 'جلسه';if(/پروژه|project/.test(s))return 'پروژه';if(/یادداشت|ایده|note/.test(s))return 'یادداشت';return 'کار';}
  function renderHome(){const ti=taskInfo(), f=minsToday(), d=completedToday().length, od=ti.open.filter(overdue).length, sc=score();const fh=focusHist().filter(x=>x.date===nowDate());const focusedDone=fh.filter(x=>x.taskId&&ti.done.some(t=>String(t.id)===String(x.taskId))).length;const normalDone=Math.max(0,d-focusedDone);return `<div class="apGrid"><div class="apCard"><h4>امتیاز بهره‌وری امروز</h4><div class="apMetric">${sc}/100</div><div class="apBar"><i style="width:${sc}%"></i></div></div><div class="apCard"><h4>خلاصه امروز</h4><div>✅ ${d} کار انجام‌شده</div><div>🎯 ${f} دقیقه تمرکز</div><div>⏰ ${od} کار عقب‌افتاده</div></div><div class="apCard"><h4>تمرکز در برابر کار عادی</h4><div>با تمرکز: ${focusedDone} کار</div><div>بدون تمرکز: ${normalDone} کار</div></div><div class="apCard"><h4>ساعت پربازده</h4><div class="apMetric" style="font-size:20px">${bestHour()}</div></div><div class="apCard apFull"><h4>الان چی کار کنم؟</h4><div id="apNowText">${esc(pickTask(read(K.energy,'medium'))?.title||'کار بازی ندارید.')}</div><div class="apRow" style="margin-top:10px"><button data-energy="low">انرژی کم</button><button data-energy="medium">متوسط</button><button data-energy="high">زیاد</button></div></div></div>`}
  function renderSchedule(){const a=read(K.blocks,[]).filter(x=>x.date===nowDate()).sort((a,b)=>a.time.localeCompare(b.time));return `<div class="apCard"><h4>تقویم زمانی امروز</h4><div class="apRow"><input id="apBlockTime" type="time" style="max-width:140px"><input id="apBlockText" placeholder="مثلاً گزارش پروژه"><button id="apAddBlock">＋ افزودن</button></div><div class="apList" id="apBlocks" style="margin-top:10px">${a.length?a.map((x,i)=>`<div class="apItem"><b>${esc(x.time)}</b> · ${esc(x.text)}</div>`).join(''):'هنوز چیزی زمان‌بندی نشده.'}</div></div>`}
  function renderInbox(){const a=read(K.inbox,[]).slice().reverse();return `<div class="apCard"><h4>Inbox هوشمند</h4><div class="apRow"><input id="apInboxText" placeholder="هرچی هست سریع بنویس…"><button id="apInboxAdd">تشخیص و ثبت</button><button id="apVoice">🎙</button></div><div class="apList" style="margin-top:10px">${a.length?a.slice(0,20).map(x=>`<div class="apItem"><span class="badge">${esc(x.type)}</span> ${esc(x.text)}</div>`).join(''):'Inbox خالی است.'}</div></div>`}
  function renderProjects(){const {D,tasks}=taskInfo(), ps=Array.isArray(D.projects)?D.projects:[];return `<div class="apGrid">${ps.length?ps.map(p=>{const pt=tasks.filter(t=>String(t.projectId||t.project_id||'')===String(p.id));const done=pt.filter(t=>t.status==='done').length, pct=pt.length?Math.round(done/pt.length*100):0,next=pt.find(t=>t.status!=='done');return `<div class="apCard"><h4>${esc(p.name||p.title||'پروژه')}</h4><div>${pct}% پیشرفت</div><div class="apBar"><i style="width:${pct}%"></i></div><div class="sub" style="margin-top:8px">قدم بعدی: ${esc(next?.title||'تعریف نشده')}</div></div>`}).join(''):'<div class="apCard">پروژه‌ای پیدا نشد.</div>'}</div>`}
  function renderTracking(){const {open}=taskInfo(), logs=timeLogs().slice().reverse();return `<div class="apCard"><h4>ثبت زمان واقعی Task</h4><div class="apRow"><select id="apTimerTask"><option value="">انتخاب کار</option>${open.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select><button id="apTimerStart">شروع زمان</button><button id="apTimerStop">پایان</button></div><div id="apTimerState" class="sub" style="margin-top:8px"></div><div class="apList" style="margin-top:10px">${logs.slice(0,10).map(x=>`<div class="apItem">${esc(x.title)} · ${x.minutes||0} دقیقه</div>`).join('')||'هنوز زمان ثبت نشده.'}</div></div>`}
  function renderReports(){const {open}=taskInfo(),done=completedToday().length,focus=minsToday(),od=open.filter(overdue).length,sc=score();const weekStart=Date.now()-6*864e5, wh=focusHist().filter(x=>(x.ts||0)>=weekStart).reduce((s,x)=>s+(+x.minutes||0),0);const tomorrow=pickTask('medium');return `<div class="apGrid"><div class="apCard"><h4>گزارش پایان روز</h4><div>کار انجام‌شده: ${done}</div><div>تمرکز: ${focus} دقیقه</div><div>عقب‌افتاده: ${od}</div><div>امتیاز: ${sc}/100</div></div><div class="apCard"><h4>گزارش هفتگی</h4><div>تمرکز ۷ روز: ${wh} دقیقه</div><div>کار باز فعلی: ${open.length}</div></div><div class="apCard"><h4>پیشنهاد فردا</h4><div>${esc(tomorrow?.title||'فعلاً کاری پیشنهاد نمی‌شود.')}</div></div><div class="apCard"><h4>یادآوری هوشمند</h4><div>${od?`${od} کار عقب افتاده؛ بهتر است یکی را همین امشب زمان‌بندی یا خرد کنی.`:'کار عقب‌افتاده نداری.'}</div></div><div class="apCard apFull"><h4>تحلیل هوشمند</h4><div id="apAIReport">برای تحلیل عمیق‌تر دکمه زیر را بزن.</div><button id="apAnalyze" style="margin-top:10px">✦ تحلیل با AI</button></div></div>`}
  function renderNotifications(){const {open}=taskInfo(), items=[];open.filter(overdue).forEach(t=>items.push('عقب‌افتاده: '+(t.title||'کار')));open.filter(dueToday).forEach(t=>items.push('امروز: '+(t.title||'کار')));if(score()<50)items.push('امتیاز بهره‌وری امروز پایین‌تر از ۵۰ است.');return `<div class="apCard"><h4>مرکز اعلان‌ها</h4><div class="apList">${items.length?items.map(x=>`<div class="apItem">🔔 ${esc(x)}</div>`).join(''):'اعلان مهمی نداری.'}</div></div>`}
  function renderBackup(){const a=read(K.backs,[]);return `<div class="apCard"><h4>بکاپ نسخه‌ای خودکار</h4><div>تعداد نسخه‌های ذخیره‌شده: ${a.length}</div><div class="sub">ARIA تا ۷ Snapshot آخر از داده محلی را نگه می‌دارد.</div><button id="apBackupNow" style="margin-top:10px">ساخت Snapshot الان</button></div>`}
  function tabHtml(tab){return tab==='schedule'?renderSchedule():tab==='inbox'?renderInbox():tab==='projects'?renderProjects():tab==='tracking'?renderTracking():tab==='reports'?renderReports():tab==='notifications'?renderNotifications():tab==='backup'?renderBackup():renderHome()}
  function ensureDialog(){if($('ariaProdDialog'))return;const d=document.createElement('dialog');d.id='ariaProdDialog';d.innerHTML=`<div><div class="sectionHead"><b>⚡ مرکز بهره‌وری ARIA</b><button class="ghost" id="apClose">بستن</button></div><div class="apTabs"><button data-tab="home">داشبورد</button><button data-tab="schedule">زمان‌بندی</button><button data-tab="inbox">Inbox</button><button data-tab="projects">پروژه‌ها</button><button data-tab="tracking">زمان Task</button><button data-tab="reports">گزارش‌ها</button><button data-tab="notifications">اعلان‌ها</button><button data-tab="backup">بکاپ</button></div><div id="apBody"></div></div>`;document.body.appendChild(d);$('apClose').onclick=()=>d.close();d.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));showTab('home')}
  function showTab(tab){const body=$('apBody');if(!body)return;document.querySelectorAll('#ariaProdDialog [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));body.innerHTML=tabHtml(tab);wire(tab)}
  function wire(tab){if(tab==='home')document.querySelectorAll('[data-energy]').forEach(b=>b.onclick=()=>{write(K.energy,b.dataset.energy);const t=pickTask(b.dataset.energy);$('apNowText').textContent=t?.title||'کاری پیدا نشد.'});
    if(tab==='schedule')$('apAddBlock').onclick=()=>{const time=$('apBlockTime').value,text=$('apBlockText').value.trim();if(!time||!text)return;const a=read(K.blocks,[]);a.push({date:nowDate(),time,text});write(K.blocks,a);showTab('schedule')};
    if(tab==='inbox'){$('apInboxAdd').onclick=()=>{const text=$('apInboxText').value.trim();if(!text)return;const a=read(K.inbox,[]);a.push({ts:Date.now(),text,type:smartClassify(text)});write(K.inbox,a.slice(-300));showTab('inbox')};$('apVoice').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('apInboxText').placeholder='تشخیص صدا در این مرورگر در دسترس نیست';return}const r=new SR();r.lang='fa-IR';r.onresult=e=>{$('apInboxText').value=e.results[0][0].transcript};r.start()}}
    if(tab==='tracking'){let active=read('ARIA_ACTIVE_TASK_TIMER_V1',null);const state=()=>{$('apTimerState').textContent=active?`در حال ثبت زمان: ${active.title}`:'تایمر Task خاموش است.'};state();$('apTimerStart').onclick=()=>{const s=$('apTimerTask'),id=s.value;if(!id)return;active={id,title:s.selectedOptions[0].textContent,start:Date.now()};write('ARIA_ACTIVE_TASK_TIMER_V1',active);state()};$('apTimerStop').onclick=()=>{active=read('ARIA_ACTIVE_TASK_TIMER_V1',null);if(!active)return;const end=Date.now(),minutes=Math.max(1,Math.round((end-active.start)/60000)),a=timeLogs();a.push({...active,end,minutes,date:nowDate()});write(K.timers,a.slice(-500));LS.removeItem('ARIA_ACTIVE_TASK_TIMER_V1');active=null;showTab('tracking')}}
    if(tab==='reports')$('apAnalyze').onclick=async()=>{const box=$('apAIReport');box.textContent='در حال تحلیل…';const {open}=taskInfo();const prompt=`امروز ${completedToday().length} کار انجام شده، ${minsToday()} دقیقه تمرکز داشتم، ${open.filter(overdue).length} کار عقب‌افتاده دارم و امتیاز بهره‌وری ${score()} از 100 است. یک تحلیل خیلی کوتاه و کاربردی فارسی بده: چه چیزی خوب بود، مشکل اصلی چه بود، فردا چه کنم.`;try{if(window.ARIA_BRAIN?.ask){const r=await window.ARIA_BRAIN.ask(prompt);box.textContent=r?.text||String(r)}else box.textContent='AI فعلاً در دسترس نیست.'}catch(e){box.textContent='تحلیل AI فعلاً در دسترس نیست.'}};
    if(tab==='backup')$('apBackupNow').onclick=()=>{snapshot();showTab('backup')};}
  function snapshot(){const D=getDB();if(!D)return;const a=read(K.backs,[]);a.push({ts:Date.now(),date:nowDate(),db:D});write(K.backs,a.slice(-7))}
  function mount(){ensureDialog();if($('ariaProdBtn'))return;const top=document.querySelector('header .top>div:last-child')||document.querySelector('.top>div:last-child');if(!top)return;const b=document.createElement('button');b.id='ariaProdBtn';b.type='button';b.title='مرکز بهره‌وری';b.textContent='⚡';b.onclick=()=>{$('ariaProdDialog').showModal();showTab('home')};top.insertBefore(b,top.firstChild)}
  let lastSnap=0;setInterval(()=>{const D=getDB();if(!D)return;const sig=JSON.stringify({t:(D.tasks||[]).length,p:(D.projects||[]).length,u:(D.tasks||[]).map(x=>x.updatedAt||x.status).slice(-20)});const h=[...sig].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0);if(h!==lastSnap){lastSnap=h;snapshot()}},300000);
  mount();new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});window.ARIA_PRODUCTIVITY_OPEN=()=>{$('ariaProdDialog')?.showModal();showTab('home')};
})();