(function(){
  if(window.__ARIA_VOICE_ENGINE_V1)return;window.__ARIA_VOICE_ENGINE_V1=true;
  const cfg=window.ARIA_CLOUD||{};
  function findToken(obj,depth=0){if(!obj||depth>6)return'';if(typeof obj==='object'){if(typeof obj.access_token==='string'&&obj.access_token.trim())return obj.access_token.trim();for(const k of Object.keys(obj)){const v=findToken(obj[k],depth+1);if(v)return v}}return''}
  function token(){try{const preferred=cfg.supabaseUrl?`sb-${new URL(cfg.supabaseUrl).hostname.split('.')[0]}-auth-token`:'';const keys=[preferred,...Object.keys(localStorage).filter(k=>k.startsWith('sb-')&&k.includes('auth-token'))].filter(Boolean);for(const k of [...new Set(keys)]){const raw=localStorage.getItem(k);if(!raw)continue;try{const t=findToken(JSON.parse(raw));if(t)return t}catch(_){}}}catch(_){}throw new Error('برای استفاده از صدا باید وارد حساب ARIA باشی.');}
  function bestMime(){if(!window.MediaRecorder)return'';for(const t of ['audio/mp4','audio/webm;codecs=opus','audio/webm']){try{if(MediaRecorder.isTypeSupported?.(t))return t}catch(_){}}return''}
  async function transcribe(blob){const t=token();const r=await fetch(`/api/aria-ai?mode=transcribe&t=${encodeURIComponent(t)}&guard=27`,{method:'POST',headers:{'Content-Type':blob.type||'audio/mp4'},body:blob});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out?.detail||out?.error||`خطای صدا ${r.status}`);const text=String(out?.text||'').trim();if(!text)throw new Error('متنی از صدا تشخیص داده نشد.');return text}
  async function startRecorder(opts={}){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('ضبط صدا روی این دستگاه در دسترس نیست.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});const mime=bestMime();const mr=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const chunks=[];let done=false;const cleanup=()=>{try{stream.getTracks().forEach(t=>t.stop())}catch(_){}};const result=new Promise((resolve,reject)=>{mr.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};mr.onerror=e=>{cleanup();reject(e.error||new Error('خطا در ضبط صدا'))};mr.onstop=async()=>{if(done)return;done=true;cleanup();try{const blob=new Blob(chunks,{type:mr.mimeType||mime||'audio/mp4'});if(blob.size<1200)throw new Error('صدا خیلی کوتاه بود؛ دوباره بگو.');opts.onState?.('در حال تبدیل صدا…');const text=await transcribe(blob);resolve(text)}catch(e){reject(e)}}});mr.start(250);opts.onState?.('دارم گوش می‌دم… برای پایان دوباره بزن.');return{stop:()=>{if(mr.state!=='inactive')mr.stop()},cancel:()=>{done=true;try{mr.stop()}catch(_){}cleanup()},result}}
  window.ARIA_VOICE_ENGINE={startRecorder,transcribe};
})();