default_platform(:ios)

platform :ios do
  lane :testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_P8_BASE64"],
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    cert(
      api_key: api_key,
      development: false,
      generate_apple_certs: true,
      output_path: "fastlane/signing"
    )

    sigh(
      api_key: api_key,
      app_identifier: "com.darisazma.mana",
      force: true,
      output_path: "fastlane/signing",
      provisioning_name: "Mana AppStore"
    )

    build_app(
      workspace: "ios/mana.xcworkspace",
      scheme: "mana",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      output_directory: "dist",
      output_name: "Mana.ipa"
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "dist/Mana.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
